name: Run checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: run StyleLint
        run: yarn stylelint

      - name: run ESLint
        if: success() || failure()
        run: yarn eslint

      # - name: run Tests
      #   if: success() || failure()
      #   run: yarn test
